apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "erd-tool.componentLabels" (list . "elasticsearch") | nindent 4 }}
spec:
  serviceName: elasticsearch-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "erd-tool.componentSelectorLabels" (list . "elasticsearch") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "erd-tool.componentSelectorLabels" (list . "elasticsearch") | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecretName }}
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts | quote }}
          ports:
            - name: http
              containerPort: 9200
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          readinessProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          {{- with .Values.elasticsearch.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.global.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storageSize }}
