server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: team-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/erdtool_team}
    username: ${SPRING_DATASOURCE_USERNAME:erdtool}
    password: ${SPRING_DATASOURCE_PASSWORD:erdtool}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: team
    open-in-view: false
  sql:
    init:
      mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
  hateoas:
    use-hal-as-default-json-media-type: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Team management API for ERD Cloud
    version: 0.0.1-SNAPSHOT

app:
  services:
    auth-service:
      url: ${AUTH_SERVICE_URL:http://localhost:8081}
    erd-service:
      url: ${ERD_SERVICE_URL:http://localhost:8083}
