apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erd-tool-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/erd-tool/erd-tool-infra.git
    targetRevision: main
    path: charts/erd-tool
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: erd-tool
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
