server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: erd-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/erdtool_erd}
    username: ${SPRING_DATASOURCE_USERNAME:erdtool}
    password: ${SPRING_DATASOURCE_PASSWORD:erdtool}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: erd
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
  hateoas:
    use-hal-as-default-json-media-type: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: ERD document API for ERD Cloud
    version: 0.0.1-SNAPSHOT

services:
  team-service:
    url: ${TEAM_SERVICE_URL:http://localhost:8082}
