import type { Dialect, ErdDocument, EntityDefinition, FieldDefinition, RelationshipDefinition } from './types';

const typeAliases: Record<Dialect, Record<string, string>> = {
  mysql: {
    bigint: 'BIGINT',
    int: 'INT',
    integer: 'INT',
    varchar: 'VARCHAR',
    text: 'TEXT',
    timestamp: 'TIMESTAMP',
    boolean: 'BOOLEAN'
  },
  mariadb: {
    bigint: 'BIGINT',
    int: 'INT',
    integer: 'INT',
    varchar: 'VARCHAR',
    text: 'TEXT',
    timestamp: 'TIMESTAMP',
    boolean: 'BOOLEAN'
  },
  oracle: {
    bigint: 'NUMBER(19)',
    int: 'NUMBER(10)',
    integer: 'NUMBER(10)',
    varchar: 'VARCHAR2',
    text: 'CLOB',
    timestamp: 'TIMESTAMP',
    boolean: 'NUMBER(1)'
  },
  postgresql: {
    bigint: 'BIGINT',
    int: 'INTEGER',
    integer: 'INTEGER',
    varchar: 'VARCHAR',
    text: 'TEXT',
    timestamp: 'TIMESTAMP',
    boolean: 'BOOLEAN'
  }
};

function resolveType(field: FieldDefinition, dialect: Dialect) {
  const alias = typeAliases[dialect][field.type.toLowerCase()] ?? field.type.toUpperCase();
  if (field.type.toLowerCase() === 'varchar' && field.length) {
    return `${alias}(${field.length})`;
  }
  return alias;
}

function primaryKeyIdentity(dialect: Dialect) {
  if (dialect === 'mysql' || dialect === 'mariadb') return 'AUTO_INCREMENT';
  if (dialect === 'oracle') return 'GENERATED BY DEFAULT AS IDENTITY';
  return 'GENERATED BY DEFAULT AS IDENTITY';
}

function columnLine(field: FieldDefinition, dialect: Dialect) {
  const parts = [`  ${field.name} ${resolveType(field, dialect)}`];
  if (field.primaryKey && ['mysql', 'mariadb', 'oracle', 'postgresql'].includes(dialect)) {
    parts.push(primaryKeyIdentity(dialect));
  }
  if (!field.nullable) parts.push('NOT NULL');
  if (field.defaultValue) parts.push(`DEFAULT ${field.defaultValue}`);
  if (field.primaryKey && dialect === 'oracle') parts.push('PRIMARY KEY');
  return parts.join(' ');
}

function buildTable(entity: EntityDefinition, dialect: Dialect) {
  const columns = entity.fields.map((field) => columnLine(field, dialect));
  const primaryKeys = entity.fields.filter((field) => field.primaryKey).map((field) => field.name);
  const constraints: string[] = [];
  if (primaryKeys.length && dialect !== 'oracle') {
    constraints.push(`  PRIMARY KEY (${primaryKeys.join(', ')})`);
  }
  return [
    `CREATE TABLE ${entity.name} (`,
    [...columns, ...constraints].join(',\n'),
    ');'
  ].join('\n');
}

function buildForeignKeys(
  entity: EntityDefinition,
  relationships: RelationshipDefinition[],
  entities: EntityDefinition[]
) {
  const owned = relationships.filter((relationship) => relationship.targetEntityId === entity.id);
  return owned.flatMap((relationship) => {
    const targetField = entity.fields.find((field) => field.id === relationship.targetFieldId);
    const sourceEntity = entities.find((item) => item.id === relationship.sourceEntityId);
    const sourceField = sourceEntity?.fields.find((field) => field.id === relationship.sourceFieldId) ?? sourceEntity?.fields[0];
    if (!targetField || !sourceEntity || !sourceField) return [];
    return [
      `ALTER TABLE ${entity.name} ADD CONSTRAINT fk_${entity.name}_${targetField.name} FOREIGN KEY (${targetField.name}) REFERENCES ${sourceEntity.name}(${sourceField.name});`
    ];
  });
}

export function generateDdl(document: ErdDocument, dialect: Dialect) {
  const tableStatements = document.entities.map((entity) => buildTable(entity, dialect));
  const fkStatements = document.entities.flatMap((entity) => buildForeignKeys(entity, document.relationships, document.entities));
  const header = `-- ${document.title} | ${dialect.toUpperCase()}`;
  return [header, ...tableStatements, ...fkStatements].join('\n\n');
}
